# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TestTerminalCommand
                                 A QGIS plugin
 This plugin is the very first one to check the procedure
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-03-06
        copyright            : (C) 2019 by Diego Pajarito
        email                : diegopajarito@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TestTerminalCommand class from file TestTerminalCommand.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .test_terminal import TestTerminalCommand
    return TestTerminalCommand(iface)
